name = "Create Astral"
author = "Laskyyy"
version = "v2.0.5b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8817c02f0b3af05aaa89e9c552784d1f446efd667bf0163e42cc09be66c5d1a7"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
