name = "Create Astral"
author = "Laskyyy"
version = "v2.0.5b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7935ad9fe46986b6e02aaa8a3b50e41486e10c31477082ca82f9c51c10114f10"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
